### ISSUE TITLE
tougher gromnir GPWSLAY.bcs causes install errors

### ISSUE THREAD

**Issue by agb1** [whiteagnus/Ascension#1]
http://www.shsforums.net/topic/56670-big-world-setup-an-attempt-to-update-the-program/page-116#entry584584

**Comment by whiteagnus** [comment]
That's not a bug in ascension, that's a "bug" in weidu (I think in BG2:EE only...)
http://forums.pocketplane.net/index.php/topic,29380.0.html

This could be fixed through three ways:
1. Using the newest Weidu beta 238.01 (http://forums.pocketplane.net/index.php/topic,29409.0.html) installing the mods, which masspatches the scripts 
2. We could remove "0 ANYONE" from EA.ids (I think we don't need it...)
3. We add something like this to the mods, which got this error: REPLACE_TEXTUALLY ~\(Allegiance(.*,\)ANYONE)~ ~\10)~

I think the best solution is using the newest Weidu beta... ;)

**Comment by whiteagnus** [comment]
I added the 2nd fix as a temporary component (999) to the current build, until a stable version of weidu is out. :)

I think this is all I can do for now... -> closed
